---
title: "Homework 5 solutions"
author: "Rio Yan"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 9,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

Describe the raw data:we have 51 cities


Read in the data.

```{r}
homicide_df = 
  read_csv("homicide_data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```


Let's look at this a bit

```{r}
aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)
) %>% 
  broom::tidy()
```

Try to iterate ...

```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```


```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2


import one dataset 

```{r}
data_1 = read_csv("lda_data/con_01.csv")
```

```{r}
path_df = 
  tibble(
    path = list.files("lda_data"),
  ) %>% 
  mutate(
    path = str_c("lda_data/", path),
    data = map(.x = path, ~read_csv(.x)),
    ) %>% 
  separate(path, into = c("cut", "path"), sep = "/") %>%
  separate(path, into = c("control_arm", "subject_id")) %>% ####warning message???
  select(-cut) %>% 
  unnest(data)
```

plot
```{r}
path_df_graph =
  path_df %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week_num",
    values_to = "value"
  ) 

path_df_graph %>% 
  ggplot(aes(x = week_num, y = value, 
             group = subject_id, color = factor(subject_id))) +
  geom_line() + geom_point() +
  facet_grid(. ~ control_arm) +
  labs(title = "Observations on each subject between two groups",
       x = "Week Number",
       y = "Value") +
  guides(color = guide_legend(title = "Subject ID")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Comment on the differences between groups:
overall the graph shows that experimental group has higher value than control group, both from the start and in the end. 









